### PR TITLE
start code tests with Python matrix

### LINKED ISSUE #6: Add unit tests workflow, including matrix of Python versions
> I'm not happy adding pins that do something already accomplished by package management software. We must not start that. Clearly conda can resolve the package requirements and it is not necessary to pin to a fixed version.
> 
> State your technical reasons.

Pinning makes sure that when the package is deployed, it is done so with the exact set of dependencies the team tested with. Bugs will still happen, but it’s much more reliable and consistent than using loose versioning, where the dependencies can vary and cause unexpected issues. As was shown above in Pyarrow not being able to be resolved.

_Originally posted by @MDecarabas in https://github.com/prjemian/model_instrument/issues/5#issuecomment-2408176269_

### PR DESCRIPTION
**Pull request by prjemian**
- close #6

### CODE REVIEW

**Review by MDecarabas — CHANGES_REQUESTED** [review]
What are the commands required for me to successfully run the testing code

**Comment by prjemian** [comment]
Just the tests: `pytest ./src` in the project's root directory.

You can see the results from the CI runs on GitHub: https://github.com/prjemian/model_instrument/actions/workflows/code.yml

If you want to run the CI code locally, install [nektos/act](https://github.com/nektos/act), then run: `act -j test-matrix`.  You'll need docker for this.

**Comment by MDecarabas** [comment]
for some reason I cannot see the tests in tests_general running, and I only see the coveralls.  I might be missing something about how to get those to run.

**Comment by prjemian** [comment]
verbosity?  `pytest -vvv --lf ./src`  (lots of verbosity, only run failed if last run had some)

**Comment by prjemian** [comment]
First format is quite terse.

**Comment by prjemian** [comment]
```bash
(model_instrument_env) prjemian@arf:~/.../prjemian/model_instrument$ pytest -vvv --lf ./src/
==================================================================================================================================== test session starts ====================================================================================================================================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0 -- /home/prjemian/.conda/envs/model_instrument_env/bin/python3.12
cachedir: .pytest_cache
rootdir: /home/prjemian/Documents/projects/prjemian/model_instrument
configfile: pyproject.toml
plugins: anyio-4.6.0
collected 5 items                                                                                                                                                                                                                                                                           
run-last-failure: no previously failed tests, not deselecting items.

src/instrument/tests/test_general.py::test_startup PASSED                                                                                                                                                                                                                             [ 20%]
src/instrument/tests/test_general.py::test_sim_plans[sim_print_plan-0] PASSED                                                                                                                                                                                                         [ 40%]
src/instrument/tests/test_general.py::test_sim_plans[sim_count_plan-1] PASSED                                                                                                                                                                                                         [ 60%]
src/instrument/tests/test_general.py::test_sim_plans[sim_rel_scan_plan-1] PASSED                                                                                                                                                                                                      [ 80%]
src/instrument/tests/test_general.py::test_iconfig PASSED                                                                                                                                                                                                                             [100%]

===================================================================================================================================== 5 passed in 2.64s =====================================================================================================================================
(model_instrument_env) prjemian@arf:~/.../prjemian/model_instrument$ 
```

**Comment by MDecarabas** [comment]
> First format is quite terse.

 

> verbosity? `pytest -vvv --lf ./src` (lots of verbosity, only run failed if last run had some)

great! Is this test also running as a workflow and can we add this line to the README under a tests header?

**Comment by prjemian** [comment]
yes and yes.

**Comment by prjemian** [comment]
https://github.com/prjemian/model_instrument/blob/b5bcdb1fe77c53af3d62b2dff9f71da669d6faca/.github/workflows/code.yml#L115

**Comment by MDecarabas** [comment]
> yes and yes.

Awesome, let's make the changes and then I'll approve it!

**Review by MDecarabas — APPROVED** [review]

**Pull request merged**
