### PR TITLE
MNT #2 rebuild the session logging

### LINKED ISSUE #2: Review and revise logging
[Following temporary change in PR #5, added this list of requirements, including features from instrument package predecessor.]

## Logging Requirements

- [x] Configuration described in `.yml` file.
- [x] Log messages to console should be brief.
  - [x] Specify date format.
  - [x] Specify log format.
- [x] Log messages to file should be descriptive.
  - [x] Specify date format.
  - [x] Specify log format.
  - [x] Describe path to log file directory.
  - [x] Specify number of backup files to keep.
  - [x] Specify maximum size of each backup file.
- [x] Specify log level for each module.

<details>
<summary>original report</summary>

Compare the logging reports from these three branches:

### startup  from the main branch

```py
(bluesky_2024_3) $ ipython -c "from instrument.startup import *"
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/prjemian/Documents/projects/prjemian/model_instrument/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Wed-16:31:54 - ############################################################ startup
I Wed-16:31:54 - logging started
I Wed-16:31:54 - logging level = 10
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/_logging_setup.py
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/aps_dm_setup.py
W Wed-16:31:54 - APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/debug_setup.py
Exception reporting mode: Minimal
I Wed-16:31:54 - xmode exception level: 'Minimal'
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/functions.py
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/mpl_setup.py
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/startup.py
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/best_effort.py
I Wed-16:31:54 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/catalog.py
I Wed-16:31:55 - Databroker catalog: temp
I Wed-16:31:55 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/ophyd_setup.py
I Wed-16:31:55 - using ophyd control layer: 'pyepics'
I Wed-16:31:55 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/run_engine.py
I Wed-16:31:55 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/epics_setup.py
I Wed-16:31:55 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/metadata.py
I Wed-16:31:55 - RunEngine metadata saved in directory: /home/prjemian/.config/Bluesky_RunEngine_md
I Wed-16:31:55 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/tests/common.py
```

### `er_test` branch

```py
(bluesky_2024_3) $ ipython -c "from instrument.startup import *"
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/prjemian/Documents/projects/prjemian/model_instrument/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Wed-16:35:13 - ############################################################ startup
I Wed-16:35:13 - logging started
I Wed-16:35:13 - logging level = 10
I Wed-16:35:13 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/_logging_setup.py
I Wed-16:35:13 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/aps_helper.py
I Wed-16:35:13 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/helper.py
Exception reporting mode: Minimal
I Wed-16:35:13 - xmode exception level: 'Minimal'
test 



ipython



is not notebook



W Wed-16:35:13 - APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Wed-16:35:13 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/ophyd_setup.py
I Wed-16:35:13 - using ophyd control layer: 'pyepics'
```

### `er_test-specwriter-fix` branch

```py
(bluesky_2024_3) $ ipython -c "from instrument.startup import *"
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/prjemian/Documents/projects/prjemian/model_instrument/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Wed-16:36:08 - ############################################################ startup
I Wed-16:36:08 - logging started
I Wed-16:36:08 - logging level = 10
I Wed-16:36:08 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/_logging_setup.py
I Wed-16:36:08 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/aps_helper.py
I Wed-16:36:08 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/helper.py
Exception reporting mode: Minimal
I Wed-16:36:08 - xmode exception level: 'Minimal'
test 



ipython



is not notebook



W Wed-16:36:08 - APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Wed-16:36:08 - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/ophyd_setup.py
I Wed-16:36:08 - using ophyd control layer: 'pyepics'
```

</details>

### PR DESCRIPTION
**Pull request by prjemian**
- close #2

Rebuild the session logging following the Python logging howto.

### CODE REVIEW

**Comment by prjemian** [comment]
It will take some work to understand how to control logging of each module at the handler level (as suggested by [bluesky](https://blueskyproject.io/bluesky/main/debugging.html)).  That could be an upgrade.

**Review by MDecarabas — CHANGES_REQUESTED** [review]
```
I Mon-12:40:25.264: **************************************** startup
I Mon-12:40:25.264: /Users/ecodrea/model_instrument/src/instrument/utils/logging_setup.py
I Mon-12:40:25.264: Log file: /Users/ecodrea/model_instrument/.logs/logging.log
Activating auto-logging. Current session state plus future input saved.
Filename       : /Users/ecodrea/model_instrument/.logs/ipython_log.py
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Mon-12:40:25.264: Console logging: /Users/ecodrea/model_instrument/.logs/ipython_log.py
I Mon-12:40:25.264: /Users/ecodrea/model_instrument/src/instrument/startup.py
I Mon-12:40:25.265: /Users/ecodrea/model_instrument/src/instrument/utils/aps_functions.py
I Mon-12:40:25.587: /Users/ecodrea/model_instrument/src/instrument/utils/helper_functions.py
Exception reporting mode: Minimal
I Mon-12:40:25.588: xmode exception level: 'Minimal'
W Mon-12:40:25.777: APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Mon-12:40:25.895: /Users/ecodrea/model_instrument/src/instrument/core/best_effort_init.py
I Mon-12:40:26.298: /Users/ecodrea/model_instrument/src/instrument/core/catalog_init.py
I Mon-12:40:26.969: Databroker catalog: temp
I Mon-12:40:26.985: /Users/ecodrea/model_instrument/src/instrument/utils/controls_setup.py
I Mon-12:40:27.059: /Users/ecodrea/model_instrument/src/instrument/utils/metadata.py
I Mon-12:40:27.059: RunEngine metadata saved in directory: /Users/ecodrea/.config/Bluesky_RunEngine_md
I Mon-12:40:27.059: /Users/ecodrea/model_instrument/src/instrument/core/run_engine_init.py
I Mon-12:40:27.060: using ophyd control layer: 'pyepics'
I Mon-12:40:27.117: /Users/ecodrea/model_instrument/src/instrument/callbacks/spec_data_file_writer.py
I Mon-12:40:27.118: SPEC data file: /Users/ecodrea/model_instrument/20241014-124027.dat
I Mon-12:40:27.178: /Users/ecodrea/model_instrument/src/instrument/tests/sim_plans.py
```

A lot of logging which is not informative. It can be kept but by no means should it be the default. This much information results in eye glazing over the text unless you know what is important. Highlighted below is the stuff that should appear.  

```
Log Filename       : /Users/ecodrea/model_instrument/.logs/ipython_log.py
W Mon-12:40:25.777: APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Mon-12:40:26.969: Databroker catalog: temp
I Mon-12:40:27.059: RunEngine metadata saved in directory: /Users/ecodrea/.config/Bluesky_RunEngine_md
I Mon-12:40:27.060: using ophyd control layer: 'pyepics'
I Mon-12:40:27.118: SPEC data file: /Users/ecodrea/model_instrument/20241014-124027.dat
```

**Comment by prjemian** [comment]
Can investigate how to attenuate.  You've identified two separate categories, both at the INFO level.  Got any ideas how to differentiate?

**Comment by MDecarabas** [comment]
> Can investigate how to attenuate. You've identified two separate categories, both at the INFO level. Got any ideas how to differentiate?

We can move it out of info inside of debug

**Comment by prjemian** [comment]
DEBUG gets lost in the noise of other debugging.

**Comment by prjemian** [comment]
Let's leave it as-is for now, seeking opinion from the community on log detail.

**Comment by prjemian** [comment]
@MDecarabas Can you change settings in `configs/logging.yml` to achieve what you describe?

**Comment by prjemian** [comment]
And, a change a couple of the `logger.info(__file__)` lines to `logger.debug(__file__)` as examples.

**Comment by prjemian** [comment]
Now, console log shows

```
Below are the logging settings for your session.
These settings have no impact on your experiment.

W Mon-17:20:09.753: APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Mon-17:20:10.838: Databroker catalog: temp
I Mon-17:20:10.909: RunEngine metadata saved in directory: /home/prjemian/.config/Bluesky_RunEngine_md
I Mon-17:20:10.911: using ophyd control layer: 'pyepics'
I Mon-17:20:10.968: SPEC data file: /home/prjemian/Documents/projects/prjemian/model_instrument/20241014-172010.dat
```

log file shows:

```
|2024-10-14 17:20:09.158|INFO|4084163|root|logging_setup|170|MainThread| - **************************************** Bluesky Startup Initialized
|2024-10-14 17:20:09.158|BSDEV|4084163|root|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/logging_setup.py
|2024-10-14 17:20:09.158|BSDEV|4084163|root|logging_setup|73|MainThread| - Log file: /home/prjemian/Documents/projects/prjemian/model_instrument/.logs/logging.log
|2024-10-14 17:20:09.390|BSDEV|4084163|instrument.utils.aps_functions|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/aps_functions.py
|2024-10-14 17:20:09.699|BSDEV|4084163|instrument.utils.helper_functions|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/helper_functions.py
|2024-10-14 17:20:09.753|WARNING|4084163|instrument.utils.aps_functions|aps_functions|48|MainThread| - APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
|2024-10-14 17:20:09.871|BSDEV|4084163|instrument.core.best_effort_init|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/best_effort_init.py
|2024-10-14 17:20:10.449|BSDEV|4084163|instrument.core.catalog_init|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/catalog_init.py
|2024-10-14 17:20:10.838|INFO|4084163|instrument.core.catalog_init|catalog_init|29|MainThread| - Databroker catalog: temp
|2024-10-14 17:20:10.839|BSDEV|4084163|instrument.utils.controls_setup|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/controls_setup.py
|2024-10-14 17:20:10.909|BSDEV|4084163|instrument.utils.metadata|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/utils/metadata.py
|2024-10-14 17:20:10.909|INFO|4084163|instrument.utils.metadata|metadata|65|MainThread| - RunEngine metadata saved in directory: /home/prjemian/.config/Bluesky_RunEngine_md
|2024-10-14 17:20:10.909|BSDEV|4084163|instrument.core.run_engine_init|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/core/run_engine_init.py
|2024-10-14 17:20:10.911|INFO|4084163|instrument.utils.controls_setup|controls_setup|88|MainThread| - using ophyd control layer: 'pyepics'
|2024-10-14 17:20:10.911|BSDEV|4084163|instrument.startup|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/startup.py
|2024-10-14 17:20:10.968|BSDEV|4084163|instrument.callbacks.spec_data_file_writer|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/callbacks/spec_data_file_writer.py
|2024-10-14 17:20:10.968|INFO|4084163|instrument.callbacks.spec_data_file_writer|spec_data_file_writer|80|MainThread| - SPEC data file: /home/prjemian/Documents/projects/prjemian/model_instrument/20241014-172010.dat
|2024-10-14 17:20:10.999|BSDEV|4084163|instrument.tests.sim_plans|logging_setup|73|MainThread| - /home/prjemian/Documents/projects/prjemian/model_instrument/src/instrument/tests/sim_plans.py
```

**Comment by prjemian** [comment]
I'm not seeing any output these lines describe:

```
Below are the logging settings for your session.
These settings have no impact on your experiment.
```

**Comment by MDecarabas** [comment]
> I'm not seeing any output these lines describe:
> 
> ```
> Below are the logging settings for your session.
> These settings have no impact on your experiment.
> ```
> 
> Ok, to suppress these, too?

Might have something to do with ssh method. This is what I get on my Mac and linux workstations:

```
I Tue-09:56:07.704: **************************************** Bluesky Startup Initialized

Below are the logging settings for your session.
These settings have no impact on your experiment.

Activating auto-logging. Current session state plus future input saved.
Filename       : /Users/ecodrea/model_instrument/.logs/ipython_log.py
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
Exception reporting mode: Minimal

End of IPython settings

W Tue-09:56:08.215: APS DM setup file does not exist: '/home/dm/etc/dm.setup.sh'
I Tue-09:56:09.478: Databroker catalog: temp
I Tue-09:56:09.545: RunEngine metadata saved in directory: /Users/ecodrea/.config/Bluesky_RunEngine_md
I Tue-09:56:09.548: using ophyd control layer: 'pyepics'
I Tue-09:56:09.624: SPEC data file: /Users/ecodrea/model_instrument/20241015-095609.dat
```

**Comment by prjemian** [comment]
> Might have something to do with  ...

You are right.  My quick test used python, rather than ipython.  I'll move the print so it only shows with ipython.

**Comment by prjemian** [comment]
@MDecarabas Ready for review

**Review by MDecarabas — APPROVED** [review]

**Pull request merged**
